mqtt:
  host: localhost
  port: 1883

host.address: 192.168.46.131
rcn:
  binders:
    message:
      enable: true
      default: mqtt
      brokerUrl: localhost
      brokerPort: 1883
      mqtt:
        producer:
          messages-to-ior:
            destination: rcn.elfie.ior.messages